/*
 * Selling Partner API for Orders
 * Use the Orders Selling Partner API to programmatically retrieve order information. With this API, you can develop fast, flexible, and custom applications to manage order synchronization, perform order research, and create demand-based decision support tools.   _Note:_ For the JP, AU, and SG marketplaces, the Orders API supports orders from 2016 onward. For all other marketplaces, the Orders API supports orders for the last two years (orders older than this don't show up in the response).
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AssociationType;
import java.io.IOException;

/**
 * An item that is associated with an order item. For example, a tire installation service that is purchased with tires.
 */
@ApiModel(description = "An item that is associated with an order item. For example, a tire installation service that is purchased with tires.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-10-31T20:07:17.661+08:00")
public class AssociatedItem {
  @SerializedName("OrderId")
  private String orderId = null;

  @SerializedName("OrderItemId")
  private String orderItemId = null;

  @SerializedName("AssociationType")
  private AssociationType associationType = null;

  public AssociatedItem orderId(String orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * The order item&#39;s order identifier, in 3-7-7 format.
   * @return orderId
  **/
  @ApiModelProperty(value = "The order item's order identifier, in 3-7-7 format.")
  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public AssociatedItem orderItemId(String orderItemId) {
    this.orderItemId = orderItemId;
    return this;
  }

   /**
   * An Amazon-defined item identifier for the associated item.
   * @return orderItemId
  **/
  @ApiModelProperty(value = "An Amazon-defined item identifier for the associated item.")
  public String getOrderItemId() {
    return orderItemId;
  }

  public void setOrderItemId(String orderItemId) {
    this.orderItemId = orderItemId;
  }

  public AssociatedItem associationType(AssociationType associationType) {
    this.associationType = associationType;
    return this;
  }

   /**
   * Get associationType
   * @return associationType
  **/
  @ApiModelProperty(value = "")
  public AssociationType getAssociationType() {
    return associationType;
  }

  public void setAssociationType(AssociationType associationType) {
    this.associationType = associationType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssociatedItem associatedItem = (AssociatedItem) o;
    return Objects.equals(this.orderId, associatedItem.orderId) &&
        Objects.equals(this.orderItemId, associatedItem.orderItemId) &&
        Objects.equals(this.associationType, associatedItem.associationType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderId, orderItemId, associationType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssociatedItem {\n");
    
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    orderItemId: ").append(toIndentedString(orderItemId)).append("\n");
    sb.append("    associationType: ").append(toIndentedString(associationType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

