/*
 * Selling Partner API for Pricing
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer pricing information for Amazon Marketplace products.  For more information, refer to the [Product Pricing v2022-05-01 Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v2022-05-01-use-case-guide).
 *
 * OpenAPI spec version: 2022-05-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CompetitiveSummaryIncludedData;
import io.swagger.client.model.HttpMethod;
import io.swagger.client.model.LowestPricedOffersInput;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * An individual &#x60;competitiveSummary&#x60; request for an ASIN and &#x60;marketplaceId&#x60;.
 */
@ApiModel(description = "An individual `competitiveSummary` request for an ASIN and `marketplaceId`.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-10-31T20:08:31.630+08:00")
public class CompetitiveSummaryRequest {
  @SerializedName("asin")
  private String asin = null;

  @SerializedName("marketplaceId")
  private String marketplaceId = null;

  @SerializedName("includedData")
  private List<CompetitiveSummaryIncludedData> includedData = new ArrayList<CompetitiveSummaryIncludedData>();

  @SerializedName("lowestPricedOffersInputs")
  private List<LowestPricedOffersInput> lowestPricedOffersInputs = null;

  @SerializedName("method")
  private HttpMethod method = null;

  @SerializedName("uri")
  private String uri = null;

  public CompetitiveSummaryRequest asin(String asin) {
    this.asin = asin;
    return this;
  }

   /**
   * The Amazon identifier for the item.
   * @return asin
  **/
  @ApiModelProperty(required = true, value = "The Amazon identifier for the item.")
  public String getAsin() {
    return asin;
  }

  public void setAsin(String asin) {
    this.asin = asin;
  }

  public CompetitiveSummaryRequest marketplaceId(String marketplaceId) {
    this.marketplaceId = marketplaceId;
    return this;
  }

   /**
   * A marketplace identifier.
   * @return marketplaceId
  **/
  @ApiModelProperty(required = true, value = "A marketplace identifier.")
  public String getMarketplaceId() {
    return marketplaceId;
  }

  public void setMarketplaceId(String marketplaceId) {
    this.marketplaceId = marketplaceId;
  }

  public CompetitiveSummaryRequest includedData(List<CompetitiveSummaryIncludedData> includedData) {
    this.includedData = includedData;
    return this;
  }

  public CompetitiveSummaryRequest addIncludedDataItem(CompetitiveSummaryIncludedData includedDataItem) {
    this.includedData.add(includedDataItem);
    return this;
  }

   /**
   * The list of requested competitive pricing data for the product.
   * @return includedData
  **/
  @ApiModelProperty(required = true, value = "The list of requested competitive pricing data for the product.")
  public List<CompetitiveSummaryIncludedData> getIncludedData() {
    return includedData;
  }

  public void setIncludedData(List<CompetitiveSummaryIncludedData> includedData) {
    this.includedData = includedData;
  }

  public CompetitiveSummaryRequest lowestPricedOffersInputs(List<LowestPricedOffersInput> lowestPricedOffersInputs) {
    this.lowestPricedOffersInputs = lowestPricedOffersInputs;
    return this;
  }

  public CompetitiveSummaryRequest addLowestPricedOffersInputsItem(LowestPricedOffersInput lowestPricedOffersInputsItem) {
    if (this.lowestPricedOffersInputs == null) {
      this.lowestPricedOffersInputs = new ArrayList<LowestPricedOffersInput>();
    }
    this.lowestPricedOffersInputs.add(lowestPricedOffersInputsItem);
    return this;
  }

   /**
   * The list of &#x60;lowestPricedOffersInput&#x60; parameters used to build the &#x60;lowestPricedOffers&#x60; in the response. This attribute is valid only if &#x60;lowestPricedOffers&#x60; is requested in &#x60;includedData&#x60;.
   * @return lowestPricedOffersInputs
  **/
  @ApiModelProperty(value = "The list of `lowestPricedOffersInput` parameters used to build the `lowestPricedOffers` in the response. This attribute is valid only if `lowestPricedOffers` is requested in `includedData`.")
  public List<LowestPricedOffersInput> getLowestPricedOffersInputs() {
    return lowestPricedOffersInputs;
  }

  public void setLowestPricedOffersInputs(List<LowestPricedOffersInput> lowestPricedOffersInputs) {
    this.lowestPricedOffersInputs = lowestPricedOffersInputs;
  }

  public CompetitiveSummaryRequest method(HttpMethod method) {
    this.method = method;
    return this;
  }

   /**
   * HTTP method type
   * @return method
  **/
  @ApiModelProperty(required = true, value = "HTTP method type")
  public HttpMethod getMethod() {
    return method;
  }

  public void setMethod(HttpMethod method) {
    this.method = method;
  }

  public CompetitiveSummaryRequest uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * The URI associated with the individual APIs being called as part of the batch request. For &#x60;getCompetitiveSummary&#x60;, this should be &#x60;/products/pricing/2022-05-01/items/competitiveSummary&#x60;.
   * @return uri
  **/
  @ApiModelProperty(required = true, value = "The URI associated with the individual APIs being called as part of the batch request. For `getCompetitiveSummary`, this should be `/products/pricing/2022-05-01/items/competitiveSummary`.")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompetitiveSummaryRequest competitiveSummaryRequest = (CompetitiveSummaryRequest) o;
    return Objects.equals(this.asin, competitiveSummaryRequest.asin) &&
        Objects.equals(this.marketplaceId, competitiveSummaryRequest.marketplaceId) &&
        Objects.equals(this.includedData, competitiveSummaryRequest.includedData) &&
        Objects.equals(this.lowestPricedOffersInputs, competitiveSummaryRequest.lowestPricedOffersInputs) &&
        Objects.equals(this.method, competitiveSummaryRequest.method) &&
        Objects.equals(this.uri, competitiveSummaryRequest.uri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(asin, marketplaceId, includedData, lowestPricedOffersInputs, method, uri);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompetitiveSummaryRequest {\n");
    
    sb.append("    asin: ").append(toIndentedString(asin)).append("\n");
    sb.append("    marketplaceId: ").append(toIndentedString(marketplaceId)).append("\n");
    sb.append("    includedData: ").append(toIndentedString(includedData)).append("\n");
    sb.append("    lowestPricedOffersInputs: ").append(toIndentedString(lowestPricedOffersInputs)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

