/*
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * OpenAPI spec version: 2020-07-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.DeliveryDocumentList;
import io.swagger.client.model.DropOffLocation;
import java.io.IOException;

/**
 * The delivery information for the package. This information is available after the package is delivered.
 */
@ApiModel(description = "The delivery information for the package. This information is available after the package is delivered.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-10-31T19:59:58.801+08:00")
public class DeliveryInformation {
  @SerializedName("deliveryDocumentList")
  private DeliveryDocumentList deliveryDocumentList = null;

  @SerializedName("dropOffLocation")
  private DropOffLocation dropOffLocation = null;

  public DeliveryInformation deliveryDocumentList(DeliveryDocumentList deliveryDocumentList) {
    this.deliveryDocumentList = deliveryDocumentList;
    return this;
  }

   /**
   * All of the delivery documents for a package.
   * @return deliveryDocumentList
  **/
  @ApiModelProperty(value = "All of the delivery documents for a package.")
  public DeliveryDocumentList getDeliveryDocumentList() {
    return deliveryDocumentList;
  }

  public void setDeliveryDocumentList(DeliveryDocumentList deliveryDocumentList) {
    this.deliveryDocumentList = deliveryDocumentList;
  }

  public DeliveryInformation dropOffLocation(DropOffLocation dropOffLocation) {
    this.dropOffLocation = dropOffLocation;
    return this;
  }

   /**
   * The drop off location for a package.
   * @return dropOffLocation
  **/
  @ApiModelProperty(value = "The drop off location for a package.")
  public DropOffLocation getDropOffLocation() {
    return dropOffLocation;
  }

  public void setDropOffLocation(DropOffLocation dropOffLocation) {
    this.dropOffLocation = dropOffLocation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeliveryInformation deliveryInformation = (DeliveryInformation) o;
    return Objects.equals(this.deliveryDocumentList, deliveryInformation.deliveryDocumentList) &&
        Objects.equals(this.dropOffLocation, deliveryInformation.dropOffLocation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deliveryDocumentList, dropOffLocation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeliveryInformation {\n");
    
    sb.append("    deliveryDocumentList: ").append(toIndentedString(deliveryDocumentList)).append("\n");
    sb.append("    dropOffLocation: ").append(toIndentedString(dropOffLocation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

