/*
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * OpenAPI spec version: 2020-07-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Destination;
import io.swagger.client.model.Origin;
import java.io.IOException;

/**
 * The delivery terms for the delivery offer.
 */
@ApiModel(description = "The delivery terms for the delivery offer.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-10-31T19:59:58.801+08:00")
public class GetDeliveryOffersTerms {
  @SerializedName("origin")
  private Origin origin = null;

  @SerializedName("destination")
  private Destination destination = null;

  public GetDeliveryOffersTerms origin(Origin origin) {
    this.origin = origin;
    return this;
  }

   /**
   * The origin for the delivery offer.
   * @return origin
  **/
  @ApiModelProperty(required = true, value = "The origin for the delivery offer.")
  public Origin getOrigin() {
    return origin;
  }

  public void setOrigin(Origin origin) {
    this.origin = origin;
  }

  public GetDeliveryOffersTerms destination(Destination destination) {
    this.destination = destination;
    return this;
  }

   /**
   * The destination for the delivery offer.
   * @return destination
  **/
  @ApiModelProperty(required = true, value = "The destination for the delivery offer.")
  public Destination getDestination() {
    return destination;
  }

  public void setDestination(Destination destination) {
    this.destination = destination;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetDeliveryOffersTerms getDeliveryOffersTerms = (GetDeliveryOffersTerms) o;
    return Objects.equals(this.origin, getDeliveryOffersTerms.origin) &&
        Objects.equals(this.destination, getDeliveryOffersTerms.destination);
  }

  @Override
  public int hashCode() {
    return Objects.hash(origin, destination);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDeliveryOffersTerms {\n");
    
    sb.append("    origin: ").append(toIndentedString(origin)).append("\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

