/*
 * Selling Partner API for Pricing
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer pricing information for Amazon Marketplace products.  For more information, refer to the [Product Pricing v2022-05-01 Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v2022-05-01-use-case-guide).
 *
 * OpenAPI spec version: 2022-05-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.FeaturedOfferExpectedPriceResponseList;
import java.io.IOException;

/**
 * The response schema for the &#x60;getFeaturedOfferExpectedPriceBatch&#x60; operation.
 */
@ApiModel(description = "The response schema for the `getFeaturedOfferExpectedPriceBatch` operation.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-10-31T20:08:31.630+08:00")
public class GetFeaturedOfferExpectedPriceBatchResponse {
  @SerializedName("responses")
  private FeaturedOfferExpectedPriceResponseList responses = null;

  public GetFeaturedOfferExpectedPriceBatchResponse responses(FeaturedOfferExpectedPriceResponseList responses) {
    this.responses = responses;
    return this;
  }

   /**
   * Get responses
   * @return responses
  **/
  @ApiModelProperty(value = "")
  public FeaturedOfferExpectedPriceResponseList getResponses() {
    return responses;
  }

  public void setResponses(FeaturedOfferExpectedPriceResponseList responses) {
    this.responses = responses;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetFeaturedOfferExpectedPriceBatchResponse getFeaturedOfferExpectedPriceBatchResponse = (GetFeaturedOfferExpectedPriceBatchResponse) o;
    return Objects.equals(this.responses, getFeaturedOfferExpectedPriceBatchResponse.responses);
  }

  @Override
  public int hashCode() {
    return Objects.hash(responses);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetFeaturedOfferExpectedPriceBatchResponse {\n");
    
    sb.append("    responses: ").append(toIndentedString(responses)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

