/*
 * Selling Partner API for Supply Sources
 * Manage configurations and capabilities of seller supply sources.
 *
 * OpenAPI spec version: 2020-07-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.DeliveryChannel;
import io.swagger.client.model.OperationalConfiguration;
import io.swagger.client.model.PickupChannel;
import io.swagger.client.model.ReturnLocation;
import java.io.IOException;

/**
 * The outbound capability of a supply source.
 */
@ApiModel(description = "The outbound capability of a supply source.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-10-31T20:19:44.003+08:00")
public class OutboundCapability {
  @SerializedName("isSupported")
  private Boolean isSupported = null;

  @SerializedName("operationalConfiguration")
  private OperationalConfiguration operationalConfiguration = null;

  @SerializedName("returnLocation")
  private ReturnLocation returnLocation = null;

  @SerializedName("deliveryChannel")
  private DeliveryChannel deliveryChannel = null;

  @SerializedName("pickupChannel")
  private PickupChannel pickupChannel = null;

  public OutboundCapability isSupported(Boolean isSupported) {
    this.isSupported = isSupported;
    return this;
  }

   /**
   * Get isSupported
   * @return isSupported
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsSupported() {
    return isSupported;
  }

  public void setIsSupported(Boolean isSupported) {
    this.isSupported = isSupported;
  }

  public OutboundCapability operationalConfiguration(OperationalConfiguration operationalConfiguration) {
    this.operationalConfiguration = operationalConfiguration;
    return this;
  }

   /**
   * Get operationalConfiguration
   * @return operationalConfiguration
  **/
  @ApiModelProperty(value = "")
  public OperationalConfiguration getOperationalConfiguration() {
    return operationalConfiguration;
  }

  public void setOperationalConfiguration(OperationalConfiguration operationalConfiguration) {
    this.operationalConfiguration = operationalConfiguration;
  }

  public OutboundCapability returnLocation(ReturnLocation returnLocation) {
    this.returnLocation = returnLocation;
    return this;
  }

   /**
   * Get returnLocation
   * @return returnLocation
  **/
  @ApiModelProperty(value = "")
  public ReturnLocation getReturnLocation() {
    return returnLocation;
  }

  public void setReturnLocation(ReturnLocation returnLocation) {
    this.returnLocation = returnLocation;
  }

  public OutboundCapability deliveryChannel(DeliveryChannel deliveryChannel) {
    this.deliveryChannel = deliveryChannel;
    return this;
  }

   /**
   * Get deliveryChannel
   * @return deliveryChannel
  **/
  @ApiModelProperty(value = "")
  public DeliveryChannel getDeliveryChannel() {
    return deliveryChannel;
  }

  public void setDeliveryChannel(DeliveryChannel deliveryChannel) {
    this.deliveryChannel = deliveryChannel;
  }

  public OutboundCapability pickupChannel(PickupChannel pickupChannel) {
    this.pickupChannel = pickupChannel;
    return this;
  }

   /**
   * Get pickupChannel
   * @return pickupChannel
  **/
  @ApiModelProperty(value = "")
  public PickupChannel getPickupChannel() {
    return pickupChannel;
  }

  public void setPickupChannel(PickupChannel pickupChannel) {
    this.pickupChannel = pickupChannel;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OutboundCapability outboundCapability = (OutboundCapability) o;
    return Objects.equals(this.isSupported, outboundCapability.isSupported) &&
        Objects.equals(this.operationalConfiguration, outboundCapability.operationalConfiguration) &&
        Objects.equals(this.returnLocation, outboundCapability.returnLocation) &&
        Objects.equals(this.deliveryChannel, outboundCapability.deliveryChannel) &&
        Objects.equals(this.pickupChannel, outboundCapability.pickupChannel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isSupported, operationalConfiguration, returnLocation, deliveryChannel, pickupChannel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OutboundCapability {\n");
    
    sb.append("    isSupported: ").append(toIndentedString(isSupported)).append("\n");
    sb.append("    operationalConfiguration: ").append(toIndentedString(operationalConfiguration)).append("\n");
    sb.append("    returnLocation: ").append(toIndentedString(returnLocation)).append("\n");
    sb.append("    deliveryChannel: ").append(toIndentedString(deliveryChannel)).append("\n");
    sb.append("    pickupChannel: ").append(toIndentedString(pickupChannel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

