/*
 * Selling Partner API for Supply Sources
 * Manage configurations and capabilities of seller supply sources.
 *
 * OpenAPI spec version: 2020-07-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The type of parking spot identification.
 */
@JsonAdapter(ParkingSpotIdentificationType.Adapter.class)
public enum ParkingSpotIdentificationType {
  
  NUMBERED("Numbered"),
  
  OTHER("Other");

  private String value;

  ParkingSpotIdentificationType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ParkingSpotIdentificationType fromValue(String text) {
    for (ParkingSpotIdentificationType b : ParkingSpotIdentificationType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<ParkingSpotIdentificationType> {
    @Override
    public void write(final JsonWriter jsonWriter, final ParkingSpotIdentificationType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ParkingSpotIdentificationType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ParkingSpotIdentificationType.fromValue(String.valueOf(value));
    }
  }
}

