/*
 * Selling Partner API for Orders
 * Use the Orders Selling Partner API to programmatically retrieve order information. With this API, you can develop fast, flexible, and custom applications to manage order synchronization, perform order research, and create demand-based decision support tools.   _Note:_ For the JP, AU, and SG marketplaces, the Orders API supports orders from 2016 onward. For all other marketplaces, the Orders API supports orders for the last two years (orders older than this don't show up in the response).
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.UpdateVerificationStatusRequestBody;
import java.io.IOException;

/**
 * The request body for the &#x60;updateVerificationStatus&#x60; operation.
 */
@ApiModel(description = "The request body for the `updateVerificationStatus` operation.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-10-31T20:07:17.661+08:00")
public class UpdateVerificationStatusRequest {
  @SerializedName("regulatedOrderVerificationStatus")
  private UpdateVerificationStatusRequestBody regulatedOrderVerificationStatus = null;

  public UpdateVerificationStatusRequest regulatedOrderVerificationStatus(UpdateVerificationStatusRequestBody regulatedOrderVerificationStatus) {
    this.regulatedOrderVerificationStatus = regulatedOrderVerificationStatus;
    return this;
  }

   /**
   * The updated values of the &#x60;VerificationStatus&#x60; field.
   * @return regulatedOrderVerificationStatus
  **/
  @ApiModelProperty(required = true, value = "The updated values of the `VerificationStatus` field.")
  public UpdateVerificationStatusRequestBody getRegulatedOrderVerificationStatus() {
    return regulatedOrderVerificationStatus;
  }

  public void setRegulatedOrderVerificationStatus(UpdateVerificationStatusRequestBody regulatedOrderVerificationStatus) {
    this.regulatedOrderVerificationStatus = regulatedOrderVerificationStatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateVerificationStatusRequest updateVerificationStatusRequest = (UpdateVerificationStatusRequest) o;
    return Objects.equals(this.regulatedOrderVerificationStatus, updateVerificationStatusRequest.regulatedOrderVerificationStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(regulatedOrderVerificationStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateVerificationStatusRequest {\n");
    
    sb.append("    regulatedOrderVerificationStatus: ").append(toIndentedString(regulatedOrderVerificationStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

