/*
 * Selling Partner API for FBA Inventory
 * The Selling Partner API for FBA Inventory lets you programmatically retrieve information about inventory in Amazon's fulfillment network.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AddInventoryRequest;
import io.swagger.client.model.AddInventoryResponse;
import io.swagger.client.model.CreateInventoryItemRequest;
import io.swagger.client.model.CreateInventoryItemResponse;
import io.swagger.client.model.DeleteInventoryItemResponse;
import io.swagger.client.model.GetInventorySummariesResponse;
import org.threeten.bp.OffsetDateTime;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.amazon.SellingPartnerAPIAA.LWAException;

/**
* API tests for FbaInventoryApi
*/
@Ignore
public class FbaInventoryApiTest {

private final FbaInventoryApi api = new FbaInventoryApi();


/**
* 
*
* Requests that Amazon add items to the Sandbox Inventory with desired amount of quantity in the sandbox environment. This is a sandbox-only operation and must be directed to a sandbox endpoint. Refer to [Selling Partner API sandbox](https://developer-docs.amazon.com/sp-api/docs/the-selling-partner-api-sandbox) for more information.
*
* @throws ApiException if the Api call fails
* @throws LWAException If calls to fetch LWA access token fails
*/
@Test
public void addInventoryTest() throws ApiException, LWAException {
    String xAmznIdempotencyToken = null;
    AddInventoryRequest addInventoryRequestBody = null;
AddInventoryResponse response = api.addInventory(xAmznIdempotencyToken, addInventoryRequestBody);

// TODO: test validations
}

/**
* 
*
* Requests that Amazon create product-details in the Sandbox Inventory in the sandbox environment. This is a sandbox-only operation and must be directed to a sandbox endpoint. Refer to [Selling Partner API sandbox](https://developer-docs.amazon.com/sp-api/docs/the-selling-partner-api-sandbox) for more information.
*
* @throws ApiException if the Api call fails
* @throws LWAException If calls to fetch LWA access token fails
*/
@Test
public void createInventoryItemTest() throws ApiException, LWAException {
    CreateInventoryItemRequest createInventoryItemRequestBody = null;
CreateInventoryItemResponse response = api.createInventoryItem(createInventoryItemRequestBody);

// TODO: test validations
}

/**
* 
*
* Requests that Amazon Deletes an item from the Sandbox Inventory in the sandbox environment. This is a sandbox-only operation and must be directed to a sandbox endpoint. Refer to [Selling Partner API sandbox](https://developer-docs.amazon.com/sp-api/docs/the-selling-partner-api-sandbox) for more information.
*
* @throws ApiException if the Api call fails
* @throws LWAException If calls to fetch LWA access token fails
*/
@Test
public void deleteInventoryItemTest() throws ApiException, LWAException {
    String sellerSku = null;
    String marketplaceId = null;
DeleteInventoryItemResponse response = api.deleteInventoryItem(sellerSku, marketplaceId);

// TODO: test validations
}

/**
* 
*
* Returns a list of inventory summaries. The summaries returned depend on the presence or absence of the startDateTime, sellerSkus and sellerSku parameters:  - All inventory summaries with available details are returned when the startDateTime, sellerSkus and sellerSku parameters are omitted. - When startDateTime is provided, the operation returns inventory summaries that have had changes after the date and time specified. The sellerSkus and sellerSku parameters are ignored. Important: To avoid errors, use both startDateTime and nextToken to get the next page of inventory summaries that have changed after the date and time specified. - When the sellerSkus parameter is provided, the operation returns inventory summaries for only the specified sellerSkus. The sellerSku parameter is ignored. - When the sellerSku parameter is provided, the operation returns inventory summaries for only the specified sellerSku.  Note: The parameters associated with this operation may contain special characters that must be encoded to successfully call the API. To avoid errors with SKUs when encoding URLs, refer to [URL Encoding](https://developer-docs.amazon.com/sp-api/docs/url-encoding).  Usage Plan:  | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 2 |  The x-amzn-RateLimit-Limit response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits).
*
* @throws ApiException if the Api call fails
* @throws LWAException If calls to fetch LWA access token fails
*/
@Test
public void getInventorySummariesTest() throws ApiException, LWAException {
    String granularityType = null;
    String granularityId = null;
    List<String> marketplaceIds = null;
    Boolean details = null;
    OffsetDateTime startDateTime = null;
    List<String> sellerSkus = null;
    String sellerSku = null;
    String nextToken = null;
GetInventorySummariesResponse response = api.getInventorySummaries(granularityType, granularityId, marketplaceIds, details, startDateTime, sellerSkus, sellerSku, nextToken);

// TODO: test validations
}

}