/*
 * Selling Partner API for Supply Sources
 * Manage configurations and capabilities of seller supply sources.
 *
 * OpenAPI spec version: 2020-07-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import java.math.BigDecimal;
import io.swagger.client.model.CreateSupplySourceRequest;
import io.swagger.client.model.CreateSupplySourceResponse;
import io.swagger.client.model.ErrorList;
import io.swagger.client.model.GetSupplySourcesResponse;
import io.swagger.client.model.SupplySource;
import io.swagger.client.model.UpdateSupplySourceRequest;
import io.swagger.client.model.UpdateSupplySourceStatusRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.amazon.SellingPartnerAPIAA.LWAException;

/**
* API tests for SupplySourcesApi
*/
@Ignore
public class SupplySourcesApiTest {

private final SupplySourcesApi api = new SupplySourcesApi();


/**
* 
*
* Archive a supply source, making it inactive. Cannot be undone.
*
* @throws ApiException if the Api call fails
* @throws LWAException If calls to fetch LWA access token fails
*/
@Test
public void archiveSupplySourceTest() throws ApiException, LWAException {
    String supplySourceId = null;
ErrorList response = api.archiveSupplySource(supplySourceId);

// TODO: test validations
}

/**
* 
*
* Create a new supply source.
*
* @throws ApiException if the Api call fails
* @throws LWAException If calls to fetch LWA access token fails
*/
@Test
public void createSupplySourceTest() throws ApiException, LWAException {
    CreateSupplySourceRequest payload = null;
CreateSupplySourceResponse response = api.createSupplySource(payload);

// TODO: test validations
}

/**
* 
*
* Retrieve a supply source.
*
* @throws ApiException if the Api call fails
* @throws LWAException If calls to fetch LWA access token fails
*/
@Test
public void getSupplySourceTest() throws ApiException, LWAException {
    String supplySourceId = null;
SupplySource response = api.getSupplySource(supplySourceId);

// TODO: test validations
}

/**
* 
*
* The path to retrieve paginated supply sources.
*
* @throws ApiException if the Api call fails
* @throws LWAException If calls to fetch LWA access token fails
*/
@Test
public void getSupplySourcesTest() throws ApiException, LWAException {
    String nextPageToken = null;
    BigDecimal pageSize = null;
GetSupplySourcesResponse response = api.getSupplySources(nextPageToken, pageSize);

// TODO: test validations
}

/**
* 
*
* Update the configuration and capabilities of a supply source.
*
* @throws ApiException if the Api call fails
* @throws LWAException If calls to fetch LWA access token fails
*/
@Test
public void updateSupplySourceTest() throws ApiException, LWAException {
    String supplySourceId = null;
    UpdateSupplySourceRequest payload = null;
ErrorList response = api.updateSupplySource(supplySourceId, payload);

// TODO: test validations
}

/**
* 
*
* Update the status of a supply source.
*
* @throws ApiException if the Api call fails
* @throws LWAException If calls to fetch LWA access token fails
*/
@Test
public void updateSupplySourceStatusTest() throws ApiException, LWAException {
    String supplySourceId = null;
    UpdateSupplySourceStatusRequest payload = null;
ErrorList response = api.updateSupplySourceStatus(supplySourceId, payload);

// TODO: test validations
}

}